### PR TITLE
Updated README.MD - Compatible with WebODM Cloud Dataset Import

### PR DESCRIPTION
**Pull request by Saijin-Naib**
Update all GitHub links for the datasets to reference the Tree/Branch model, to be compatible with the WebODM Cloud Dataset Import function.

### CODE REVIEW

**Comment by pierotofy** [comment]
Looks good to me! :+1:

**Comment by pierotofy** [comment]
Thanks @Saijin-Naib

**Comment by smathermather** [comment]
Ha! That's awesome.

**Comment by Saijin-Naib** [comment]
I still think the Right Solution (TM) is to modify the Cloud Import function to not need the trunk/branch style GitHub links since they're far less common, but I can't figure that out yet.

**Pull request merged**
